apiVersion: v1
kind: Service
metadata:
  name: zookeeper2-clusterip-service
spec:
  type: ClusterIP
  selector:
    component: zookeeper2-service
  ports:
    - name: zookeeper-port
      port: 2181
      targetPort: 2181