apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-new-reservations-socket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: restaurant-new-reservations-socket
  template:
    metadata:
      labels:
        component: restaurant-new-reservations-socket
    spec:
      containers:
        - name: restaurant-new-reservations-socket
          image: eatout/app:restaurant-new-reservations-socket
          ports:
            - containerPort: 5011
          env:
            - name: PORT
              value: '5011'
            - name: KAFKA_HOST
              value: kafka-cluster-ip-service
            - name: KAFKA_PORT
              value: '9092'