apiVersion: v1
kind: Service
metadata:
  name: restaurant-reply-socket-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: restaurant-reply-socket
  ports:
    - name: http
      port: 5012
      targetPort: 5012