apiVersion: v1
kind: Service
metadata:
  name: restaurant-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: restaurant-service
  ports:
    - port: 5000
      targetPort: 5000