apiVersion: v1
kind: Service
metadata:
  name: customer-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: customer-service
  ports:
    - name: http
      port: 5004
      targetPort: 5004