apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: restaurant-db
  template:
    metadata:
      labels:
        component: restaurant-db
    spec:
      volumes:
        - name: restaurant-db-storage
          persistentVolumeClaim:
            claimName: restaurant-db-persistent-volume-claim
      containers:
        - name: restaurant-db
          image: eatout/app:restaurant-db
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: restaurant-db-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"