apiVersion: v1
kind: Service
metadata:
  name: status-socket-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: status-socket
  ports:
    - name: http
      port: 5013
      targetPort: 5013