apiVersion: v1
kind: Service
metadata:
  name: restaurant-login-db-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: restaurant-login-db
  ports:
    - port: 3306
      targetPort: 3306