apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-login-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: restaurant-login-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: restaurant-login-db
    spec:
      containers:
        - name: restaurant-login-db
          image: eatout/app:restaurant-login-db
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-login-db-secrets
                  key: MYSQL_ALLOW_EMPTY_PASSWORD
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "5m"
              memory: "350Mi"
            limits:
              cpu: "10m"
              memory: "400Mi"
          volumeMounts:
            - name: restaurant-login-db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: restaurant-login-db-storage
          persistentVolumeClaim:
            claimName: restaurant-login-db-persistent-volume-claim