apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka
  template:
    metadata:
      labels:
        component: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.0
          ports:
            - name: 'external'
              containerPort: 9092
            - name: 'internal'
              containerPort: 29092
            - name: 'config-port'
              containerPort: 9999
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://${MY_POD_IP}:19092,EXTERNAL://host.docker.internal:9092,DOCKER://host.docker.internal:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_INTER_BROKER_LISTENER_NAME
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_ZOOKEEPER_CONNECT
            - name: KAFKA_BROKER_ID
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_BROKER_ID
            - name: KAFKA_LOG4J_LOGGERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_LOG4J_LOGGERS
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            - name: KAFKA_JMX_PORT
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_JMX_PORT
            - name: KAFKA_JMX_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_JMX_HOSTNAME
            - name: KAFKA_AUTHORIZER_CLASS_NAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_AUTHORIZER_CLASS_NAME
            - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KAFKA_AUTO_CREATE_TOPICS_ENABLE