apiVersion: v1
kind: Service
metadata:
  name: kafka2-clusterip-service
spec:
  type: ClusterIP
  selector:
    component: kafka-broker
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
