apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-reply-socket-deployment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: restaurant-reply-socket
  template:
    metadata:
      labels:
        component: restaurant-reply-socket
    spec:
      containers:
        - name: restaurant-reply-socket
          image: eatout/app:restaurant-reply-socket
          ports:
            - containerPort: 5012
          env:
            - name: PORT
              value: '5012'
            - name: KAFKA_HOST
              value: kafka-cluster-ip-service
            - name: KAFKA_PORT
              value: '9092'