apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: zookeeper2-service
  ports:
    - name: http
      port: 2181
      targetPort: 2181