apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: account-service
  template:
    metadata:
      labels:
        component: account-service
    spec:
      containers:
        - name: account-service
          image: eatout/app:account-service-azure-test-image
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: "1m"
              memory: "50Mi"
            limits:
              cpu: "5m"
              memory: "100Mi"
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: PORT
            - name: RESTAURANT_LOGIN_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: RESTAURANT_LOGIN_DB_HOST
            - name: RESTAURANT_LOGIN_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: RESTAURANT_LOGIN_DB_PORT
            - name: RESTAURANT_LOGIN_DB_USER
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: RESTAURANT_LOGIN_DB_USER
            - name: RESTAURANT_LOGIN_DB
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: RESTAURANT_LOGIN_DB
            - name: RESTAURANT_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: RESTAURANT_SERVICE_URL
            - name: RESTAURANT_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: account-service-secrets
                  key: RESTAURANT_SERVICE_PORT