apiVersion: v1
kind: Service
metadata:
  name: corporate-client-cluster-ip-service
  labels:
    component: corporate-client-service
spec:
  type: ClusterIP
  selector:
    component: eatout-corporate
  ports:
    - port: 80
      targetPort: 80