apiVersion: v1
kind: Service
metadata:
  name: reservation-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: reservation-service
  ports:
    - name: http
      port: 5001
      targetPort: 5001