apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: account-service
  template:
    metadata:
      labels:
        component: account-service
    spec:
      containers:
        - name: account-service
          image: eatout/app:account-service
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: '5002'
            - name: RESTAURANT-LOGIN-DB-HOST
              value: restaurant-login-db-cluster-ip-service
            - name: RESTAURANT-LOGIN-DB-PORT
              value: '3306'
            - name: RESTAURANT-LOGIN-DB-USER
              value: root
            - name: RESTAURANT-LOGIN-DB
              value: db
            - name: RESTAURANT-SERVICE-HOST
              value: restaurant-service-cluster-ip-service
            - name: RESTAURANT-SERVICE-PORT
              value: '5000'