apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: customer-client
  template:
    metadata:
      labels:
        component: customer-client
    spec:
      containers:
        - name: eatout-customer-client
          image: eatout/app:azure-customer-client-test
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "1m"
              memory: "5Mi"
            limits:
              cpu: "2m"
              memory: "50Mi"