apiVersion: v1
kind: Service
metadata:
  name: customer-client-cluster-ip-service
  labels:
    component: customer-client-service
spec:
  type: ClusterIP
  selector:
    component: customer-client
  ports:
    - port: 80
      targetPort: 80