apiVersion: v1
kind: Service
metadata:
  name: create-reservation-socket-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: create-reservation-socket
  ports:
    - name: http
      port: 5010
      targetPort: 5010