apiVersion: v1
kind: Service
metadata:
  name: restaurant-new-reservations-socket-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: restaurant-new-reservations-socket
  ports:
    - name: http
      port: 5011
      targetPort: 5011