apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reservation-service
  template:
    metadata:
      labels:
        component: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: eatout/app:reservation-service
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: '5001'
            - name: RESERVATION-DB-HOST
              value: reservation-db-cluster-ip-service
            - name: RESERVATION-DB-PORT
              value: '3306'
            - name: RESERVATION-DB-USER
              value: root
            - name: RESERVATION-DB
              value: db