apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-socket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: status-socket
  template:
    metadata:
      labels:
        component: status-socket
    spec:
      containers:
        - name: status-socket
          image: eatout/app:status-socket
          ports:
            - containerPort: 5013
          env:
            - name: PORT
              value: '5013'
            - name: KAFKA_HOST
              value: kafka-cluster-ip-service
            - name: KAFKA_PORT
              value: '9092'