apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: customer-service
  template:
    metadata:
      labels:
        component: customer-service
    spec:
      containers:
        - name: eatout-customer-service
          image: eatout/app:eatout-customer-service
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: '5004'
            - name: CUSTOMER_LOGIN_DB_HOST
              value: customer-db-cluster-ip-service
            - name: CUSTOMER_LOGIN_DB_PORT
              value: '3306'
            - name: CUSTOMER_LOGIN_DB_USER
              value: root
            - name: CUSTOMER_LOGIN_DB
              value: db